import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { BarChart3, Calendar, MapPin, ChevronDown, ChevronLeft, ChevronRight } from 'lucide-react'
import client from '../api/client'
import WormChart from '../components/charts/WormChart'
import ManhattanChart from '../components/charts/ManhattanChart'
import ExportButton from '../components/ui/ExportButton'

const TABS = ['Worm Chart', 'Manhattan Chart', 'Scorecard']

export default function MatchPage() {
  const [seasons, setSeasons] = useState([])
  const [selectedSeason, setSelectedSeason] = useState(null)
  const [matches, setMatches] = useState([])
  const [selectedId, setSelectedId] = useState(null)
  const [wormData, setWormData] = useState(null)
  const [manhattanData, setManhattanData] = useState(null)
  const [scorecard, setScorecard] = useState(null)
  const [loading, setLoading] = useState(false)
  const [activeTab, setActiveTab] = useState(0)
  const [matchPage, setMatchPage] = useState(0)
  const MATCHES_PER_PAGE = 12

  // Load seasons
  useEffect(() => {
    client.get('/meta/seasons').then(r => {
      const s = r.data
      setSeasons(s)
      if (s.length > 0) setSelectedSeason(s[0].season)
    }).catch(() => {})
  }, [])

  // Load matches when season changes
  useEffect(() => {
    if (!selectedSeason) return
    setMatches([])
    setSelectedId(null)
    setWormData(null)
    setMatchPage(0)
    client.get(`/match/list?season=${selectedSeason}&limit=100`).then(r => {
      setMatches(r.data)
      if (r.data.length > 0) loadMatch(r.data[0].id)
    }).catch(() => {})
  }, [selectedSeason])

  const loadMatch = async (id) => {
    setSelectedId(id)
    setLoading(true)
    try {
      const [worm, manhattan, sc] = await Promise.all([
        client.get(`/match/${id}/worm`),
        client.get(`/match/${id}/manhattan`),
        client.get(`/match/${id}/scorecard`),
      ])
      setWormData(worm.data)
      setManhattanData(manhattan.data)
      setScorecard(sc.data)
      setActiveTab(0)
    } catch (e) { console.error(e) }
    setLoading(false)
  }

  const currentMatch = matches.find(m => m.id === selectedId)
  const pagedMatches = matches.slice(matchPage * MATCHES_PER_PAGE, (matchPage + 1) * MATCHES_PER_PAGE)
  const totalPages = Math.ceil(matches.length / MATCHES_PER_PAGE)

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">Match Analysis</h1>
          <p className="page-subtitle">Worm charts · Manhattan charts · Full scorecards</p>
        </div>
        {selectedId && <ExportButton matchId={selectedId} aiSummary="Match analysis generated by SportsMassive" />}
      </div>

      {/* Season Selector */}
      <div className="card" style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
        <div style={{ position: 'relative', minWidth: 180 }}>
          <label style={{ fontSize: '0.7rem', color: 'var(--text-muted)', display: 'block', marginBottom: 4, textTransform: 'uppercase', letterSpacing: '0.08em' }}>Season</label>
          <select className="input" value={selectedSeason || ''} onChange={e => setSelectedSeason(Number(e.target.value))}
            style={{ appearance: 'none', paddingRight: '2rem', paddingTop: '0.5rem', paddingBottom: '0.5rem' }}>
            {seasons.map(s => (
              <option key={s.season} value={s.season}>IPL {s.season} ({s.match_count} matches)</option>
            ))}
          </select>
          <ChevronDown size={13} style={{ position: 'absolute', right: '0.75rem', bottom: '0.6rem', color: 'var(--text-muted)', pointerEvents: 'none' }} />
        </div>
        {matches.length > 0 && (
          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            {matches.length} matches in IPL {selectedSeason}
          </div>
        )}
      </div>

      {/* Match Selector (paginated) */}
      {matches.length > 0 && (
        <div className="card" style={{ marginBottom: '1.25rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.625rem' }}>
            <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
              Select Match
            </span>
            {totalPages > 1 && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <button className="btn btn-ghost" style={{ padding: '0.2rem 0.4rem' }}
                  onClick={() => setMatchPage(p => Math.max(0, p-1))} disabled={matchPage === 0}>
                  <ChevronLeft size={14} />
                </button>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{matchPage+1}/{totalPages}</span>
                <button className="btn btn-ghost" style={{ padding: '0.2rem 0.4rem' }}
                  onClick={() => setMatchPage(p => Math.min(totalPages-1, p+1))} disabled={matchPage === totalPages-1}>
                  <ChevronRight size={14} />
                </button>
              </div>
            )}
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.4rem' }}>
            {pagedMatches.map(m => (
              <button key={m.id}
                className={`btn ${selectedId === m.id ? 'btn-primary' : 'btn-ghost'}`}
                style={{ fontSize: '0.72rem', padding: '0.3rem 0.65rem' }}
                onClick={() => loadMatch(m.id)}
              >
                {m.team1?.split(' ').slice(-1)[0]} vs {m.team2?.split(' ').slice(-1)[0]}
                <span style={{ opacity: 0.6, marginLeft: 4 }}>{m.match_date?.slice(5)}</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Match Header */}
      {currentMatch && (
        <motion.div key={currentMatch.id} initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
          className="card" style={{ marginBottom: '1.25rem', background: 'linear-gradient(135deg, rgba(0,212,255,0.06), rgba(99,102,241,0.06))', border: '1px solid rgba(0,212,255,0.2)' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem' }}>
            <div>
              <h2 style={{ fontFamily: 'Rajdhani', fontWeight: 700, fontSize: '1.4rem', color: 'var(--text-primary)' }}>
                {currentMatch.team1} <span style={{ color: 'var(--text-muted)' }}>vs</span> {currentMatch.team2}
              </h2>
              <div style={{ display: 'flex', gap: '1rem', marginTop: '0.35rem', flexWrap: 'wrap' }}>
                <span style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                  <MapPin size={12} /> {currentMatch.venue}
                </span>
                <span style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                  <Calendar size={12} /> {currentMatch.match_date}
                </span>
              </div>
            </div>
            <div className="badge badge-green" style={{ fontSize: '0.8rem', padding: '0.35rem 0.75rem' }}>
              🏆 {currentMatch.winner} won by {currentMatch.result_margin}
            </div>
          </div>
        </motion.div>
      )}

      {loading && <div style={{ display: 'flex', justifyContent: 'center', padding: '4rem' }}><div className="spinner" /></div>}

      {!loading && wormData && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1.25rem' }}>
            {TABS.map((tab, i) => (
              <button key={tab} className={`btn ${activeTab === i ? 'btn-primary' : 'btn-ghost'}`}
                style={{ fontSize: '0.8rem' }} onClick={() => setActiveTab(i)}>{tab}</button>
            ))}
          </div>

          {activeTab === 0 && (
            <motion.div key="worm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="card">
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1.25rem' }}>
                <BarChart3 size={16} color="var(--accent-blue)" />
                <span style={{ fontWeight: 600 }}>Match Progression — Worm Chart</span>
                <span className="badge badge-red" style={{ fontSize: '0.65rem', marginLeft: 'auto' }}>🔴 Wicket</span>
              </div>
              <WormChart data={wormData} />
            </motion.div>
          )}

          {activeTab === 1 && (
            <motion.div key="manhattan" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="card">
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1.25rem' }}>
                <BarChart3 size={16} color="var(--accent-indigo)" />
                <span style={{ fontWeight: 600 }}>Runs Per Over — Manhattan Chart</span>
                <span className="badge badge-amber" style={{ fontSize: '0.65rem', marginLeft: 'auto' }}>🟡 15+ runs = big over</span>
              </div>
              <ManhattanChart data={manhattanData} />
            </motion.div>
          )}

          {activeTab === 2 && scorecard && (
            <motion.div key="scorecard" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
              {scorecard.scorecard?.map(inn => (
                <div key={inn.innings} className="card" style={{ marginBottom: '1rem' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                    <div style={{ fontFamily: 'Rajdhani', fontWeight: 700, fontSize: '1.1rem', color: 'var(--accent-blue)' }}>
                      {inn.batting_team} — Innings {inn.innings}
                    </div>
                    <div className="badge badge-blue" style={{ fontSize: '0.8rem' }}>
                      {inn.total_runs}/{inn.total_wickets}
                    </div>
                  </div>
                  <div style={{ overflowX: 'auto' }}>
                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                      <thead>
                        <tr style={{ borderBottom: '1px solid var(--border)' }}>
                          {['Batter','Runs','Balls','SR','4s','6s','Dismissal'].map(h => (
                            <th key={h} style={{ padding: '0.5rem 0.75rem', textAlign: 'left', color: 'var(--text-muted)', fontWeight: 600, whiteSpace: 'nowrap' }}>{h}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {inn.batting?.map((b, i) => (
                          <tr key={i} style={{ borderBottom: '1px solid var(--border)' }}>
                            <td style={{ padding: '0.5rem 0.75rem', fontWeight: 600 }}>{b.batter}</td>
                            <td style={{ padding: '0.5rem 0.75rem', color: 'var(--accent-blue)', fontWeight: 700 }}>{b.runs}</td>
                            <td style={{ padding: '0.5rem 0.75rem' }}>{b.balls}</td>
                            <td style={{ padding: '0.5rem 0.75rem', color: 'var(--accent-emerald)' }}>{b.sr}</td>
                            <td style={{ padding: '0.5rem 0.75rem' }}>{b.fours}</td>
                            <td style={{ padding: '0.5rem 0.75rem', color: 'var(--accent-amber)' }}>{b.sixes}</td>
                            <td style={{ padding: '0.5rem 0.75rem', color: 'var(--text-muted)', fontSize: '0.75rem', textTransform: 'capitalize' }}>{b.dismissal || 'not out'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                  {inn.bowling?.length > 0 && (
                    <div style={{ marginTop: '1rem', paddingTop: '1rem', borderTop: '1px solid var(--border)' }}>
                      <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '0.5rem' }}>Bowling</div>
                      <div style={{ overflowX: 'auto' }}>
                        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                          <thead>
                            <tr style={{ borderBottom: '1px solid var(--border)' }}>
                              {['Bowler','Overs','Runs','Wkts','Economy'].map(h => (
                                <th key={h} style={{ padding: '0.4rem 0.75rem', textAlign: 'left', color: 'var(--text-muted)', fontWeight: 600 }}>{h}</th>
                              ))}
                            </tr>
                          </thead>
                          <tbody>
                            {inn.bowling.map((b, i) => (
                              <tr key={i} style={{ borderBottom: '1px solid var(--border)' }}>
                                <td style={{ padding: '0.4rem 0.75rem', fontWeight: 600 }}>{b.bowler}</td>
                                <td style={{ padding: '0.4rem 0.75rem' }}>{b.overs}</td>
                                <td style={{ padding: '0.4rem 0.75rem' }}>{b.runs}</td>
                                <td style={{ padding: '0.4rem 0.75rem', color: 'var(--accent-red)', fontWeight: 700 }}>{b.wickets}</td>
                                <td style={{ padding: '0.4rem 0.75rem', color: 'var(--accent-amber)' }}>{b.economy}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </motion.div>
          )}
        </motion.div>
      )}

      {!loading && !wormData && matches.length === 0 && selectedSeason && (
        <div style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-muted)' }}>
          No matches found for IPL {selectedSeason}
        </div>
      )}
    </div>
  )
}
